# numpy get started

In [ ]:
python: 一切皆对象
linux: 一切皆文件.
数据分析: 一切皆矩阵

导入numpy库，并查看numpy版本

In [1]:
import numpy as  np

In [2]:
np.__version__

'1.16.3'

In [3]:
!pip install matplotlib -i https://pypi.douban.com/simple

Looking in indexes: https://pypi.douban.com/simple


In [4]:
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
#  读取猫的图片
cat = plt.imread('cat.jpg')

In [6]:
!pip install pillow -i https://pypi.douban.com/simple

Looking in indexes: https://pypi.douban.com/simple


In [ ]:
numpy 里面的矩阵不是真正的矩阵, 只是numpy用来表示矩阵的一种数据结构, 叫做ndarray

In [8]:
cat

array([[[231, 186, 131],
        [232, 187, 132],
        [233, 188, 133],
        ...,
        [100,  55,  52],
        [ 92,  48,  49],
        [ 85,  43,  44]],

       [[232, 187, 132],
        [232, 187, 132],
        [233, 188, 133],
        ...,
        [100,  55,  52],
        [ 92,  48,  49],
        [ 84,  42,  43]],

       [[232, 187, 132],
        [233, 188, 133],
        [233, 188, 133],
        ...,
        [ 99,  54,  51],
        [ 91,  47,  48],
        [ 83,  41,  42]],

       ...,

       [[199, 119,  82],
        [199, 119,  82],
        [200, 120,  83],
        ...,
        [189,  99,  64],
        [187,  97,  62],
        [187,  97,  62]],

       [[199, 119,  82],
        [199, 119,  82],
        [199, 119,  82],
        ...,
        [188,  98,  64],
        [188,  95,  62],
        [188,  95,  62]],

       [[199, 119,  82],
        [199, 119,  82],
        [199, 119,  82],
        ...,
        [188,  98,  64],
        [188,  95,  62],
        [188,  95,  62]]

In [ ]:
cat是一个彩色图片.
jpg的结尾的图片,里面RGB颜色值都是0到255的整数.
png结尾的图片,里面RBG颜色值都是0到1的浮点数.

In [ ]:
[[[1,2,3,4], [3,4,5,6]], [[1,2,3,4], [3,4,5,6]]]

In [ ]:
unsigned int8 0 到255

## 一、创建ndarray

### 1. 使用np.array()由python list创建

参数为列表：
[1, 4, 2, 5, 3]

In [11]:
l = [1, 4, 2, '5', 3.0]
n = np.array(l)
n

array(['1', '4', '2', '5', '3.0'], dtype='<U11')

In [13]:
n[0] = 2

In [14]:
n

array(['2', '4', '2', '5', '3.0'], dtype='<U11')

In [15]:
l

[1, 4, 2, '5', 3.0]

In [16]:
l[0] = 10

In [17]:
n

array(['2', '4', '2', '5', '3.0'], dtype='<U11')

注意：
- numpy默认ndarray的所有元素的类型是相同的
- 如果传进来的列表中包含不同的类型，则统一为同一类型，优先级：str>float>int

### 2. 使用np的routines函数创建

包含以下常见创建方法：

1) np.ones(shape, dtype=None, order='C')

In [18]:
# 用来产生全是1的ndarray
# shape是用来指定ndarray的形状
# dtype是数字的类型
np.ones(shape=(8,8), dtype=np.int8)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

2) np.zeros(shape, dtype=float, order='C')

In [19]:
# 全是0 的ndarray
np.zeros(shape=(8,8), dtype=np.float32)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [21]:
np.zeros(shape=(8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

3) np.full(shape, fill_value, dtype=None, order='C')

In [22]:
# 按照指定数字产生ndarray
np.full(shape=(8,8), fill_value=8.)

array([[8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8.]])

4) np.eye(N, M=None, k=0, dtype=float)  
对角线为1其他的位置为0

In [25]:
# 生成对角线全是1,其他位置全是0的2维ndarray
# k=0 表示主对角线的索引.
np.eye(8, k=1)
#像这种主对角线全是1, 其他位置全是0的矩阵,我们叫做单位矩阵.
# 任何矩阵乘于他的单位矩阵,等于他本身.
# 如果一个矩阵可以通过矩阵的行列式变化为单位矩阵,那么说明这个矩阵有唯一的解.

array([[0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
x + y = 10 
x - y = 5
问, x,y?
x= 7.5  y = 2.5
2x = 15 -> x = 7.5

1   1  
1  -1

1  0 
1  -1

1   0
0   1

5) np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [ ]:
line space

In [28]:
# endpoint是否包含stop的值
# retstep是否返回步长.
np.linspace(0, 100, num=30, endpoint=False, retstep=True)

(array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
        16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ,
        33.33333333, 36.66666667, 40.        , 43.33333333, 46.66666667,
        50.        , 53.33333333, 56.66666667, 60.        , 63.33333333,
        66.66666667, 70.        , 73.33333333, 76.66666667, 80.        ,
        83.33333333, 86.66666667, 90.        , 93.33333333, 96.66666667]),
 3.3333333333333335)

6) np.arange([start, ]stop, [step, ]dtype=None)

In [29]:
range(0,10)

range(0, 10)

In [30]:
# 就把np.arange当成numpy版本的range
# 使用np.arange的时候,尽量用整形参数.
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
np.arange(0.1, 11.1, step=0.33333)

array([ 0.1    ,  0.43333,  0.76666,  1.09999,  1.43332,  1.76665,
        2.09998,  2.43331,  2.76664,  3.09997,  3.4333 ,  3.76663,
        4.09996,  4.43329,  4.76662,  5.09995,  5.43328,  5.76661,
        6.09994,  6.43327,  6.7666 ,  7.09993,  7.43326,  7.76659,
        8.09992,  8.43325,  8.76658,  9.09991,  9.43324,  9.76657,
       10.0999 , 10.43323, 10.76656, 11.09989])

7) np.random.randint(low, high=None, size=None, dtype='l')

In [33]:
# 左闭右开区间
np.random.randint(0, 100, size=(3,4,5))

array([[[ 9, 38, 75, 49, 13],
        [73, 18, 39,  7, 71],
        [22, 85, 86, 12, 68],
        [33, 97, 92,  9, 30]],

       [[88, 66,  2, 89, 32],
        [66, 75, 66, 44, 44],
        [16, 25, 81, 65, 23],
        [ 4, 41, 75, 38, 60]],

       [[29,  1, 20, 65, 36],
        [87, 97, 45, 55, 98],
        [83, 69, 38, 79, 81],
        [34, 63, 37, 21, 11]]])

In [ ]:
伪随机数

In [52]:
np.random.seed(1)
# np.random.RandomState(1)
np.random.randint(0, 100, size=(3,4,5))

TypeError: Cannot cast array from dtype('O') to dtype('int64') according to the rule 'safe'

8) np.random.randn(d0, d1, ..., dn)  

标准正太分布

In [56]:
# 平均值为0, 方差为1的正态分布, 就是标准正态分布.
n = np.random.randn(1000, 30, 2)
n

array([[[ 0.2417245 , -0.13442333],
        [-1.43883521,  0.97956799],
        [ 0.80008192,  0.07879758],
        ...,
        [-0.28925432,  1.1580739 ],
        [-0.30037247,  0.6645509 ],
        [-2.76945753, -0.08097926]],

       [[-0.66989768, -1.4265402 ],
        [ 0.5000688 , -2.19200205],
        [ 0.31185756, -1.41502372],
        ...,
        [-0.11257678,  0.43355503],
        [-0.03794933,  1.10559519],
        [ 0.82978447, -1.16713308]],

       [[ 0.59728335, -0.72799834],
        [-1.81314641,  0.12681659],
        [ 1.42865215, -1.24211919],
        ...,
        [-1.40614072, -0.67194331],
        [ 0.16350741,  0.65366082],
        [ 1.44879147,  1.22874855]],

       ...,

       [[-0.37043577,  0.91578079],
        [ 0.9186561 ,  0.78078868],
        [-0.19189495, -1.4034421 ],
        ...,
        [-0.9400336 ,  0.48619898],
        [-2.05374717,  1.59797249],
        [-1.08271494, -0.20625176]],

       [[-0.13592778, -0.68868828],
        [ 0.83733686,  0.36

9)np.random.normal(loc=0.0, scale=1.0, size=None)

In [53]:
# 正态分布 也叫高斯分布
# 概率密度曲线
# loc = location 
# scale = 
n = np.random.normal(loc=10, scale=3, size=(10000, 2))
n

array([[11.51807729,  6.36315749],
       [ 9.08079118,  9.63744275],
       [12.79913444, 12.41166113],
       ...,
       [ 7.73764589,  9.00154904],
       [ 9.98214402, 12.19151284],
       [11.61179222, 12.32280034]])

In [54]:
n.mean()

9.99526303211945

In [55]:
n.std()

3.018610240584875

10) np.random.random(size=None)  

生成0到1的随机数，左闭右开

In [57]:
np.random.random(size=(1000, 200, 50))

array([[[0.57210795, 0.29222842, 0.14202408, ..., 0.52098942,
         0.42776156, 0.10390198],
        [0.74629868, 0.63830079, 0.56734542, ..., 0.04257487,
         0.74760188, 0.05020761],
        [0.26179884, 0.47151131, 0.06576876, ..., 0.30813051,
         0.7037856 , 0.26710087],
        ...,
        [0.80890442, 0.56087178, 0.22684691, ..., 0.69710264,
         0.3092199 , 0.88868343],
        [0.04497676, 0.37504553, 0.1074436 , ..., 0.45861081,
         0.26478714, 0.17948922],
        [0.23414614, 0.94534305, 0.51228842, ..., 0.3961447 ,
         0.65589839, 0.4279652 ]],

       [[0.12592818, 0.45747296, 0.60454081, ..., 0.73542837,
         0.39537679, 0.04128584],
        [0.59746222, 0.34431164, 0.26369779, ..., 0.86675332,
         0.40873996, 0.44496789],
        [0.55567123, 0.74689184, 0.32312772, ..., 0.89664295,
         0.88151051, 0.83441817],
        ...,
        [0.14183225, 0.15759657, 0.08575352, ..., 0.30153351,
         0.98037971, 0.78373766],
        [0.0

In [61]:
np.random.random((1000,  200, 50))

array([[[3.74511968e-01, 4.55392802e-02, 4.08888063e-01, ...,
         7.95269342e-03, 3.04694099e-01, 7.73213609e-01],
        [5.92727510e-01, 8.23752522e-01, 1.76294194e-01, ...,
         8.53612327e-01, 1.07148386e-01, 1.33031729e-01],
        [6.28092820e-01, 9.88701637e-01, 1.83757359e-01, ...,
         1.10176155e-01, 1.15770176e-01, 9.52292948e-01],
        ...,
        [9.83625096e-01, 9.71594370e-01, 8.38740156e-01, ...,
         6.10472042e-01, 6.83297410e-01, 3.71054668e-01],
        [8.56243695e-01, 5.39507523e-02, 3.94243270e-01, ...,
         3.47518980e-01, 4.41340306e-01, 2.58501414e-01],
        [2.00362529e-01, 9.92788879e-01, 8.17781716e-01, ...,
         9.88461599e-01, 7.91426736e-01, 2.29824611e-01]],

       [[7.28016164e-01, 3.03448722e-01, 9.71187145e-01, ...,
         5.53291642e-01, 7.80736057e-01, 9.72834759e-01],
        [9.93878141e-01, 2.63752250e-01, 7.72490434e-02, ...,
         7.78303572e-01, 3.37231220e-01, 5.60399533e-02],
        [1.61095898e-01, 

In [ ]:
dimension 维度

In [58]:
# 和np.random.random一样
np.random.rand(100, 20, 3)

array([[[0.03797368, 0.93871338, 0.71223342],
        [0.18696404, 0.18285969, 0.749174  ],
        [0.82847294, 0.90660898, 0.65487842],
        ...,
        [0.66587153, 0.94767219, 0.0302862 ],
        [0.14517877, 0.03451033, 0.59574901],
        [0.8678393 , 0.56878485, 0.30185761]],

       [[0.1887381 , 0.1101112 , 0.92355507],
        [0.12925742, 0.01547303, 0.96302479],
        [0.60724881, 0.65323864, 0.63673453],
        ...,
        [0.73034494, 0.5114338 , 0.7083376 ],
        [0.63897543, 0.21648675, 0.68859376],
        [0.85383462, 0.62108899, 0.88962533]],

       [[0.70084569, 0.15830597, 0.6112098 ],
        [0.68508502, 0.39829192, 0.965467  ],
        [0.39425145, 0.34156001, 0.7608983 ],
        ...,
        [0.60408264, 0.66661795, 0.71956994],
        [0.45114873, 0.5119692 , 0.25770238],
        [0.60469786, 0.27457299, 0.27647694]],

       ...,

       [[0.66377205, 0.68583713, 0.70464348],
        [0.19432692, 0.47994485, 0.77379018],
        [0.09508323, 0

## 二、ndarray的属性

4个必记参数：
ndim：维度
shape：形状（各维度的长度）
size：总长度

dtype：元素类型


In [62]:
n = np.random.randint(0, 100, size=(3,4,5))
n

array([[[36, 31, 60, 84, 83],
        [30, 39,  2, 15, 97],
        [61, 75, 15, 42, 95],
        [11, 50, 69, 49, 17]],

       [[69, 81, 35, 26, 92],
        [ 6, 28, 88,  2, 79],
        [29, 49, 50, 67, 40],
        [69, 89,  4, 39, 54]],

       [[40, 43, 12, 94, 70],
        [ 0, 20, 83, 71, 32],
        [62, 80,  9, 79, 99],
        [91,  4,  1, 79, 33]]])

In [63]:
# 维度
n.ndim

3

In [64]:
n.shape

(3, 4, 5)

In [65]:
n.size

60

In [66]:
n.dtype

dtype('int32')

## 三、ndarray的基本操作

### 1. 索引
一维与列表完全一致
多维时同理

In [68]:
l = [5,2,3,1,7]
n2 = np.array(l)
n2

array([5, 2, 3, 1, 7])

In [69]:
n2[0]

5

In [70]:
l[0]

5

In [71]:
n3 = np.random.randint(0,100, size=(4,5))
n3

array([[91, 71, 78, 17, 85],
       [83, 88, 45, 56, 11],
       [91, 75, 62, 39, 46],
       [64, 74, 83, 24, 86]])

In [72]:
n3[1, 2]

45

In [73]:
n[1, 2, 2]

50

In [74]:
n4 = np.random.randint(0,100, size=(3, 4, 3, 6))
n4

array([[[[49, 10, 76, 15, 27, 69],
         [73,  0, 12, 94, 42, 41],
         [67, 66, 27, 33, 82, 29]],

        [[ 3, 57, 42, 68, 54, 50],
         [66,  9, 33, 80, 44, 50],
         [51, 87, 46, 80, 97, 73]],

        [[77, 25, 15, 15, 36, 11],
         [ 8, 95, 29, 32, 95, 43],
         [78, 92, 74, 23, 18, 93]],

        [[12, 90, 86, 39, 90, 71],
         [15, 56, 65, 30, 44, 66],
         [47, 22, 24, 12, 17, 52]]],


       [[[24, 18,  7, 29, 10, 78],
         [17, 17, 34, 27, 79,  6],
         [62, 59, 39, 32, 19, 31]],

        [[19, 56, 53, 28, 26, 50],
         [10, 98, 58, 73, 78, 41],
         [73, 84, 43,  5, 52, 59]],

        [[ 0, 26, 21, 95, 93, 56],
         [89,  4, 24,  8,  5, 90],
         [94, 27, 65, 24, 27, 59]],

        [[78, 47, 52, 97, 31, 64],
         [15,  5, 31, 34, 34, 43],
         [12, 24, 59, 78, 86, 69]]],


       [[[81, 69,  1, 38, 60,  2],
         [96, 49, 78, 26, 67, 43],
         [84, 60, 87, 26, 47, 88]],

        [[33, 37, 48, 92, 52, 69]

In [75]:
n4[0, 2, 1, 3]

32

In [76]:
n4[0, 2, 1, 3] = 88


In [77]:
n4[0, 2, 1, 3]

88

根据索引修改数据

### 2. 切片
一维与列表完全一致
多维时同理

In [78]:
l = [5,2,3,1,7]
n2 = np.array(l)
n2

array([5, 2, 3, 1, 7])

In [80]:
l[2:]

[3, 1, 7]

In [81]:
n2[2:]

array([3, 1, 7])

In [82]:
n3

array([[91, 71, 78, 17, 85],
       [83, 88, 45, 56, 11],
       [91, 75, 62, 39, 46],
       [64, 74, 83, 24, 86]])

In [83]:
n3[2:]

array([[91, 75, 62, 39, 46],
       [64, 74, 83, 24, 86]])

In [84]:
n3[2:, 1:3]

array([[75, 62],
       [74, 83]])

In [85]:
n

array([[[36, 31, 60, 84, 83],
        [30, 39,  2, 15, 97],
        [61, 75, 15, 42, 95],
        [11, 50, 69, 49, 17]],

       [[69, 81, 35, 26, 92],
        [ 6, 28, 88,  2, 79],
        [29, 49, 50, 67, 40],
        [69, 89,  4, 39, 54]],

       [[40, 43, 12, 94, 70],
        [ 0, 20, 83, 71, 32],
        [62, 80,  9, 79, 99],
        [91,  4,  1, 79, 33]]])

In [86]:
n[1, 1:3, 1:3]

array([[28, 88],
       [49, 50]])

# 将数据反转，例如[1,2,3]---->[3,2,1]

两个::进行切片

In [88]:
l

[5, 2, 3, 1, 7]

In [87]:
l[::-1]

[7, 1, 3, 2, 5]

In [89]:
n

array([[[36, 31, 60, 84, 83],
        [30, 39,  2, 15, 97],
        [61, 75, 15, 42, 95],
        [11, 50, 69, 49, 17]],

       [[69, 81, 35, 26, 92],
        [ 6, 28, 88,  2, 79],
        [29, 49, 50, 67, 40],
        [69, 89,  4, 39, 54]],

       [[40, 43, 12, 94, 70],
        [ 0, 20, 83, 71, 32],
        [62, 80,  9, 79, 99],
        [91,  4,  1, 79, 33]]])

In [92]:
n[::-1, ::-1, ::-1]

array([[[33, 79,  1,  4, 91],
        [99, 79,  9, 80, 62],
        [32, 71, 83, 20,  0],
        [70, 94, 12, 43, 40]],

       [[54, 39,  4, 89, 69],
        [40, 67, 50, 49, 29],
        [79,  2, 88, 28,  6],
        [92, 26, 35, 81, 69]],

       [[17, 49, 69, 50, 11],
        [95, 42, 15, 75, 61],
        [97, 15,  2, 39, 30],
        [83, 84, 60, 31, 36]]])

### 3. 变形
使用reshape函数

In [93]:
n

array([[[36, 31, 60, 84, 83],
        [30, 39,  2, 15, 97],
        [61, 75, 15, 42, 95],
        [11, 50, 69, 49, 17]],

       [[69, 81, 35, 26, 92],
        [ 6, 28, 88,  2, 79],
        [29, 49, 50, 67, 40],
        [69, 89,  4, 39, 54]],

       [[40, 43, 12, 94, 70],
        [ 0, 20, 83, 71, 32],
        [62, 80,  9, 79, 99],
        [91,  4,  1, 79, 33]]])

In [94]:
n.size

60

In [95]:
n.reshape(6,10)

array([[36, 31, 60, 84, 83, 30, 39,  2, 15, 97],
       [61, 75, 15, 42, 95, 11, 50, 69, 49, 17],
       [69, 81, 35, 26, 92,  6, 28, 88,  2, 79],
       [29, 49, 50, 67, 40, 69, 89,  4, 39, 54],
       [40, 43, 12, 94, 70,  0, 20, 83, 71, 32],
       [62, 80,  9, 79, 99, 91,  4,  1, 79, 33]])

In [96]:
n.reshape(10,6)

array([[36, 31, 60, 84, 83, 30],
       [39,  2, 15, 97, 61, 75],
       [15, 42, 95, 11, 50, 69],
       [49, 17, 69, 81, 35, 26],
       [92,  6, 28, 88,  2, 79],
       [29, 49, 50, 67, 40, 69],
       [89,  4, 39, 54, 40, 43],
       [12, 94, 70,  0, 20, 83],
       [71, 32, 62, 80,  9, 79],
       [99, 91,  4,  1, 79, 33]])

In [97]:
n.reshape(3,8)

ValueError: cannot reshape array of size 60 into shape (3,8)

In [ ]:
# reshape之后的size不能发生变化.

In [98]:
n.reshape((10,6))

array([[36, 31, 60, 84, 83, 30],
       [39,  2, 15, 97, 61, 75],
       [15, 42, 95, 11, 50, 69],
       [49, 17, 69, 81, 35, 26],
       [92,  6, 28, 88,  2, 79],
       [29, 49, 50, 67, 40, 69],
       [89,  4, 39, 54, 40, 43],
       [12, 94, 70,  0, 20, 83],
       [71, 32, 62, 80,  9, 79],
       [99, 91,  4,  1, 79, 33]])

In [100]:
np.reshape(n, (10,6))

array([[36, 31, 60, 84, 83, 30],
       [39,  2, 15, 97, 61, 75],
       [15, 42, 95, 11, 50, 69],
       [49, 17, 69, 81, 35, 26],
       [92,  6, 28, 88,  2, 79],
       [29, 49, 50, 67, 40, 69],
       [89,  4, 39, 54, 40, 43],
       [12, 94, 70,  0, 20, 83],
       [71, 32, 62, 80,  9, 79],
       [99, 91,  4,  1, 79, 33]])

### 4. 级联
1. np.concatenate()
级联需要注意的点：
- 级联的参数是列表：一定要加中括号或小括号
- 维度必须相同
- 形状相符
- 【重点】级联的方向默认是shape这个tuple的第一个值所代表的维度方向
- 可通过axis参数改变级联的方向

In [106]:
n1 = np.random.randint(0,100, size=(4,5))
n2 = np.random.randint(0,100, size=(4,5))
display(n1, n2)

array([[47, 56,  8, 59,  3],
       [67, 26, 25,  1, 10],
       [70,  4, 45, 91, 49],
       [40, 32, 87, 40, 50]])

array([[92, 82, 32,  8, 23],
       [17, 48, 80,  2, 92],
       [79, 25, 18,  6, 72],
       [13, 66,  0, 58,  7]])

In [102]:
# axis=0 , 增加了行数, 垂直方向级联
# axis=1 , 增加列数, 在水平方向上级联
np.concatenate((n1,n2), axis=0)

array([[78, 82, 59, 23, 64],
       [30, 94, 73,  0,  8],
       [99,  8, 65, 79, 65],
       [94, 55, 74, 94, 26],
       [56, 43, 62, 62, 58],
       [99, 41, 19, 56, 34],
       [80, 90, 90,  1, 34],
       [95, 53, 12,  4, 69]])

In [103]:
np.concatenate((n1,n2), axis=1)

array([[78, 82, 59, 23, 64, 56, 43, 62, 62, 58],
       [30, 94, 73,  0,  8, 99, 41, 19, 56, 34],
       [99,  8, 65, 79, 65, 80, 90, 90,  1, 34],
       [94, 55, 74, 94, 26, 95, 53, 12,  4, 69]])

In [ ]:
# 级联的时候,水平级联要求行数一致.
# 垂直级联,要求列数一致.

In [104]:
n1 = np.random.randint(0,100, size=(4,5))
n2 = np.random.randint(0,100, size=(5,4))
display(n1, n2)

array([[27, 24, 61, 89, 37],
       [ 4, 60, 78,  6,  3],
       [22, 86, 58,  1, 49],
       [64, 50, 44, 11, 16]])

array([[43, 29,  5,  4],
       [ 3, 31, 25, 97],
       [68, 82, 63, 66],
       [55,  4, 78, 86],
       [19, 13, 18, 30]])

In [105]:
np.concatenate((n1,n2), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

2. np.hstack与np.vstack  
水平级联与垂直级联,处理自己，进行维度的变更

In [107]:
np.hstack((n1, n2)) # h = horizontal  

array([[47, 56,  8, 59,  3, 92, 82, 32,  8, 23],
       [67, 26, 25,  1, 10, 17, 48, 80,  2, 92],
       [70,  4, 45, 91, 49, 79, 25, 18,  6, 72],
       [40, 32, 87, 40, 50, 13, 66,  0, 58,  7]])

In [108]:
np.vstack((n1,n2)) # v = vertical垂直的

array([[47, 56,  8, 59,  3],
       [67, 26, 25,  1, 10],
       [70,  4, 45, 91, 49],
       [40, 32, 87, 40, 50],
       [92, 82, 32,  8, 23],
       [17, 48, 80,  2, 92],
       [79, 25, 18,  6, 72],
       [13, 66,  0, 58,  7]])

### 5. 切分

与级联类似，三个函数完成切分工作：
- np.split
- np.vsplit
- np.hsplit

In [110]:
n2

array([[92, 82, 32,  8, 23],
       [17, 48, 80,  2, 92],
       [79, 25, 18,  6, 72],
       [13, 66,  0, 58,  7]])

In [111]:

# 左闭右开区间.
np.split(n2, [1,2] )

[array([[92, 82, 32,  8, 23]]),
 array([[17, 48, 80,  2, 92]]),
 array([[79, 25, 18,  6, 72],
        [13, 66,  0, 58,  7]])]

In [112]:
n2 = np.random.randint(0, 100, size=(7,5))
n2

array([[12, 56, 42, 81, 26],
       [19, 36, 72, 77, 91],
       [ 4, 16, 79, 85, 60],
       [75, 57, 59, 12, 37],
       [ 5, 28, 25, 85, 23],
       [70,  4, 97, 41, 82],
       [ 6, 87, 87, 72, 92]])

In [113]:
np.split(n2, [2, 5])

[array([[12, 56, 42, 81, 26],
        [19, 36, 72, 77, 91]]), array([[ 4, 16, 79, 85, 60],
        [75, 57, 59, 12, 37],
        [ 5, 28, 25, 85, 23]]), array([[70,  4, 97, 41, 82],
        [ 6, 87, 87, 72, 92]])]

In [114]:
np.split(n2, [1, 3], axis=1)

[array([[12],
        [19],
        [ 4],
        [75],
        [ 5],
        [70],
        [ 6]]), array([[56, 42],
        [36, 72],
        [16, 79],
        [57, 59],
        [28, 25],
        [ 4, 97],
        [87, 87]]), array([[81, 26],
        [77, 91],
        [85, 60],
        [12, 37],
        [85, 23],
        [41, 82],
        [72, 92]])]

In [115]:
np.hsplit(n2, [2, 5])

[array([[12, 56],
        [19, 36],
        [ 4, 16],
        [75, 57],
        [ 5, 28],
        [70,  4],
        [ 6, 87]]), array([[42, 81, 26],
        [72, 77, 91],
        [79, 85, 60],
        [59, 12, 37],
        [25, 85, 23],
        [97, 41, 82],
        [87, 72, 92]]), array([], shape=(7, 0), dtype=int32)]

In [116]:
np.vsplit(n2, [1, 3])

[array([[12, 56, 42, 81, 26]]), array([[19, 36, 72, 77, 91],
        [ 4, 16, 79, 85, 60]]), array([[75, 57, 59, 12, 37],
        [ 5, 28, 25, 85, 23],
        [70,  4, 97, 41, 82],
        [ 6, 87, 87, 72, 92]])]

### 6. 副本
所有赋值运算不会为ndarray的任何元素创建副本。对赋值后的对象的操作也对原来的对象生效。

In [117]:
n2

array([[12, 56, 42, 81, 26],
       [19, 36, 72, 77, 91],
       [ 4, 16, 79, 85, 60],
       [75, 57, 59, 12, 37],
       [ 5, 28, 25, 85, 23],
       [70,  4, 97, 41, 82],
       [ 6, 87, 87, 72, 92]])

In [118]:
n = n2

In [119]:
display(n, n2)

array([[12, 56, 42, 81, 26],
       [19, 36, 72, 77, 91],
       [ 4, 16, 79, 85, 60],
       [75, 57, 59, 12, 37],
       [ 5, 28, 25, 85, 23],
       [70,  4, 97, 41, 82],
       [ 6, 87, 87, 72, 92]])

array([[12, 56, 42, 81, 26],
       [19, 36, 72, 77, 91],
       [ 4, 16, 79, 85, 60],
       [75, 57, 59, 12, 37],
       [ 5, 28, 25, 85, 23],
       [70,  4, 97, 41, 82],
       [ 6, 87, 87, 72, 92]])

In [120]:
n[0,0] = 88

In [121]:
n

array([[88, 56, 42, 81, 26],
       [19, 36, 72, 77, 91],
       [ 4, 16, 79, 85, 60],
       [75, 57, 59, 12, 37],
       [ 5, 28, 25, 85, 23],
       [70,  4, 97, 41, 82],
       [ 6, 87, 87, 72, 92]])

In [122]:
n2

array([[88, 56, 42, 81, 26],
       [19, 36, 72, 77, 91],
       [ 4, 16, 79, 85, 60],
       [75, 57, 59, 12, 37],
       [ 5, 28, 25, 85, 23],
       [70,  4, 97, 41, 82],
       [ 6, 87, 87, 72, 92]])

可使用copy()函数创建副本

In [123]:
# 深拷贝
n = n2.copy()

In [126]:
n[0,0] =108

In [127]:
n2

array([[88, 56, 42, 81, 26],
       [19, 36, 72, 77, 91],
       [ 4, 16, 79, 85, 60],
       [75, 57, 59, 12, 37],
       [ 5, 28, 25, 85, 23],
       [70,  4, 97, 41, 82],
       [ 6, 87, 87, 72, 92]])

## 四、ndarray的聚合操作

### 1. 求和np.sum

In [128]:
n

array([[108,  56,  42,  81,  26],
       [ 19,  36,  72,  77,  91],
       [  4,  16,  79,  85,  60],
       [ 75,  57,  59,  12,  37],
       [  5,  28,  25,  85,  23],
       [ 70,   4,  97,  41,  82],
       [  6,  87,  87,  72,  92]])

In [130]:
n4

array([[[[49, 10, 76, 15, 27, 69],
         [73,  0, 12, 94, 42, 41],
         [67, 66, 27, 33, 82, 29]],

        [[ 3, 57, 42, 68, 54, 50],
         [66,  9, 33, 80, 44, 50],
         [51, 87, 46, 80, 97, 73]],

        [[77, 25, 15, 15, 36, 11],
         [ 8, 95, 29, 88, 95, 43],
         [78, 92, 74, 23, 18, 93]],

        [[12, 90, 86, 39, 90, 71],
         [15, 56, 65, 30, 44, 66],
         [47, 22, 24, 12, 17, 52]]],


       [[[24, 18,  7, 29, 10, 78],
         [17, 17, 34, 27, 79,  6],
         [62, 59, 39, 32, 19, 31]],

        [[19, 56, 53, 28, 26, 50],
         [10, 98, 58, 73, 78, 41],
         [73, 84, 43,  5, 52, 59]],

        [[ 0, 26, 21, 95, 93, 56],
         [89,  4, 24,  8,  5, 90],
         [94, 27, 65, 24, 27, 59]],

        [[78, 47, 52, 97, 31, 64],
         [15,  5, 31, 34, 34, 43],
         [12, 24, 59, 78, 86, 69]]],


       [[[81, 69,  1, 38, 60,  2],
         [96, 49, 78, 26, 67, 43],
         [84, 60, 87, 26, 47, 88]],

        [[33, 37, 48, 92, 52, 69]

In [131]:
n4.sum()

10560

In [129]:
n.sum()

1896

In [132]:
n.sum(axis=0) # 聚合运算axis=0  表示是对列操作

array([287, 284, 461, 453, 411])

In [133]:
n.sum(axis=1) # 聚合运算axis=1,表示对行操作.

array([313, 295, 244, 240, 166, 294, 344])

In [134]:
np.sum(n, axis=1)

array([313, 295, 244, 240, 166, 294, 344])

### 2. 最大最小值：np.max/ np.min
同理

In [136]:
np.max(n, axis=1)

array([108,  91,  85,  75,  85,  97,  92])

### 3. 其他聚合操作
    Function Name	NaN-safe Version	Description
    np.sum	np.nansum	Compute sum of elements
    np.prod	np.nanprod	Compute product of elements
    np.mean	np.nanmean	Compute mean of elements
    np.std	np.nanstd	Compute standard deviation
    np.var	np.nanvar	Compute variance
    np.min	np.nanmin	Find minimum value
    np.max	np.nanmax	Find maximum value
    np.argmin	np.nanargmin	Find index of minimum value
    np.argmax	np.nanargmax	Find index of maximum value
    np.median	np.nanmedian	Compute median of elements
    np.percentile	np.nanpercentile	Compute rank-based statistics of elements
    np.any	N/A	Evaluate whether any elements are true
    np.all	N/A	Evaluate whether all elements are true
    np.power 幂运算

In [175]:
n

array([0, 5, 8, 7, 4, 1, 6, 3, 9, 2])

In [176]:
n.argmin()

0

In [177]:
n.argmax()

8

np.sum 和 np.nansum 的区别
nan not a number

#### 操作文件

使用pandas打开文件president_heights.csv
获取文件中的数据

In [137]:
!pip install pandas

  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl


In [138]:
import pandas as pd

In [139]:
heights = pd.read_csv('./president_heights.csv')
heights

order                    name  height(cm)
0       1       George Washington         189
1       2              John Adams         170
2       3        Thomas Jefferson         189
3       4           James Madison         163
4       5            James Monroe         183
5       6       John Quincy Adams         171
6       7          Andrew Jackson         185
7       8        Martin Van Buren         168
8       9  William Henry Harrison         173
9      10              John Tyler         183
10     11           James K. Polk         173
11     12          Zachary Taylor         173
12     13        Millard Fillmore         175
13     14         Franklin Pierce         178
14     15          James Buchanan         183
15     16         Abraham Lincoln         193
16     17          Andrew Johnson         178
17     18        Ulysses S. Grant         173
18     19     Rutherford B. Hayes         174
19     20       James A. Garfield         183
20     21       Chester A. Arthur         183
21     23       Benjamin Harrison         168
22     25        William McKinley         170
23     26      Theodore Roosevelt         178
24     27     William Howard Taft         182
25     28          Woodrow Wilson         180
26     29       Warren G. Harding         183
27     30         Calvin Coolidge         178
28     31          Herbert Hoover         182
29     32   Franklin D. Roosevelt         188
30     33         Harry S. Truman         175
31     34    Dwight D. Eisenhower         179
32     35         John F. Kennedy         183
33     36       Lyndon B. Johnson         193
34     37           Richard Nixon         182
35     38             Gerald Ford         183
36     39            Jimmy Carter         177
37     40           Ronald Reagan         185
38     41       George H. W. Bush         188
39     42            Bill Clinton         188
40     43          George W. Bush         182
41     44            Barack Obama         185

In [142]:
data = heights['height(cm)'].values.copy()

In [143]:
data

array([189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 168, 170, 178, 182, 180,
       183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188,
       188, 182, 185], dtype=int64)

In [144]:
# 平均身高
data.mean()

179.73809523809524

In [145]:
#  最高身高
data.max()

193

In [146]:
data.min()

163

## 五、ndarray的矩阵操作

### 1. 基本矩阵操作

1) 算术运算符：
- 加减乘除

In [148]:
n + 1 # ndarray和普通单个数字运算,是各个元素分别运算.

array([[109,  57,  43,  82,  27],
       [ 20,  37,  73,  78,  92],
       [  5,  17,  80,  86,  61],
       [ 76,  58,  60,  13,  38],
       [  6,  29,  26,  86,  24],
       [ 71,   5,  98,  42,  83],
       [  7,  88,  88,  73,  93]])

In [ ]:
矩阵和矩阵运算,要求行列要完全相同.

In [155]:
n1 + n2

ValueError: operands could not be broadcast together with shapes (3,4) (4,6) 

In [159]:
display(n1, n2)

array([[6, 1, 5, 8],
       [8, 4, 8, 1],
       [9, 5, 4, 0]])

array([[0, 6, 3, 5, 4, 0],
       [5, 4, 6, 7, 8, 8],
       [4, 9, 7, 3, 7, 2],
       [3, 4, 6, 4, 8, 5]])

In [156]:
n3 = n1.copy()

In [157]:
n1 + n3

array([[12,  2, 10, 16],
       [16,  8, 16,  2],
       [18, 10,  8,  0]])

In [ ]:
普通的矩阵之间的数学运算,是对应的元素分别进行数学运算,这就要求矩阵的行列需要完全一致.

2) 矩阵积np.dot()

In [149]:
n1 = np.random.randint(0,10, size=(3,4))
n2 = np.random.randint(0,10, size=(4, 6))
np.dot(n1,  n2)

array([[ 49, 117, 107,  84, 131,  58],
       [ 55, 140, 110,  96, 128,  53],
       [ 41, 110,  85,  92, 104,  48]])

In [ ]:
矩阵的乘法,没有交换律 A.B != B.A

In [150]:
np.dot(n2, n1)

ValueError: shapes (4,6) and (3,4) not aligned: 6 (dim 1) != 3 (dim 0)

### 2. 广播机制

【重要】ndarray广播机制的两条规则
- 规则一：为缺失的维度补1
- 规则二：假定缺失元素用已有值填充


例1：
m = np.ones((2, 3))
a = np.arange(3)
求m+a

In [152]:
m = np.ones((2,3))
m

array([[1., 1., 1.],
       [1., 1., 1.]])

In [153]:
a  = np.arange(3)

In [154]:
a

array([0, 1, 2])

In [158]:
m + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
a -> [[0, 1, 2], [0, 1, 2]]

例2：
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
求a+b

In [160]:
a = np.arange(3).reshape(3,1)
a

array([[0],
       [1],
       [2]])

In [161]:
b = np.arange(3)
b

array([0, 1, 2])

In [162]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

习题
a = np.ones((4, 1))
b = np.arange(4)
求a+b

In [163]:
a = np.ones((4,1))
a

array([[1.],
       [1.],
       [1.],
       [1.]])

In [164]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [165]:
a + b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

## 六、ndarray的排序

小测验：
使用以上所学numpy的知识，对一个ndarray对象进行选择排序。  

def Sortn(x):  

代码越短越好

In [178]:
def select(arr):
    for i in range(len(arr)  -1):
        # 从剩下的ndarray中选出最小值的索引.
        index = np.argmin(arr[i:]) + i
        if arr[i] > arr[index]:
            # 交换位置
            arr[i], arr[index] = arr[index], arr[i]
    return arr

In [179]:
select(n)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1. 快速排序
np.sort()与ndarray.sort()都可以，但有区别：
- np.sort()不改变输入
- ndarray.sort()本地处理，不占用空间，但改变输入

In [ ]:
# 排序只对1维的数据有意义.

In [166]:
n = np.arange(0, 10)

In [174]:
np.random.shuffle(n)

In [168]:
n

array([3, 2, 0, 1, 4, 8, 6, 7, 5, 9])

In [169]:
# 第一种np.sort()
np.sort(n)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
n

array([3, 2, 0, 1, 4, 8, 6, 7, 5, 9])

In [171]:
# 对象的sort方法
n.sort()

In [172]:
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 部分排序

In [180]:
n = np.arange(0,100)
np.random.shuffle(n)
n

array([62, 37,  0, 91, 40, 67,  4, 48, 49, 99, 38,  6,  8,  5, 36, 65, 98,
       88, 54, 41, 28, 20, 60, 66, 87, 72, 32, 93, 33, 42,  3, 24, 95, 55,
       84, 25, 14, 10, 21, 90, 18, 11, 61, 96,  7, 12, 56, 16, 76, 35, 63,
       34, 31, 73, 58, 39, 46, 19, 43, 81, 86,  2, 44, 52, 77, 82, 17, 13,
       15, 29, 53, 89, 51, 85, 70, 79, 26, 45, 71, 80, 57, 94, 83, 23, 75,
        9, 68, 22, 59, 50, 47, 97,  1, 69, 30, 78, 64, 92, 27, 74])

In [181]:
# 找出前五个最大的数
np.partition(n, kth=-5)

array([44, 35,  0, 27, 40, 30,  4, 48, 49,  1, 38,  6,  8,  5, 36, 47, 50,
       59, 54, 41, 28, 20, 60, 22,  9, 23, 32, 57, 33, 42,  3, 24, 45, 55,
       26, 25, 14, 10, 21, 51, 18, 11, 61, 53,  7, 12, 56, 16, 29, 37, 15,
       34, 31, 13, 58, 39, 46, 19, 43, 17, 52,  2, 62, 68, 74, 82, 81, 73,
       63, 76, 64, 78, 67, 85, 70, 79, 84, 69, 71, 80, 65, 77, 83, 72, 75,
       66, 86, 90, 87, 91, 93, 92, 89, 88, 94, 95, 96, 97, 98, 99])

In [182]:
# 找出最小的五个数
np.partition(n, kth=5)

array([ 1,  2,  0,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 38, 36, 19, 39,
       13, 31, 41, 28, 20, 34, 40, 27, 23, 32, 15, 33, 42, 35, 24, 30, 37,
       26, 25, 14, 43, 21, 29, 18, 17, 16, 22, 44, 53, 56, 61, 51, 55, 57,
       60, 54, 59, 58, 50, 46, 47, 49, 48, 52, 45, 62, 86, 77, 82, 81, 73,
       63, 76, 96, 89, 90, 85, 70, 79, 84, 95, 71, 80, 93, 94, 83, 72, 75,
       87, 68, 66, 88, 98, 65, 97, 99, 69, 67, 78, 64, 92, 91, 74])

### 第一题: 创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1